name: dispatch
env:
 INPUT_VALUE: '{
        version: [10, 22, 24]
        os: [ubuntu-latest, windows-latest]"
        }'
on:
  workflow_dispatch:
    inputs:
     logLevel: 
        description: 'Log level' #⬅️ Description
        required: true #⬅️ Whether required
        default: 'warning' #⬅️ Default value
        type: choice # ⬅️ Field type. This has a specific list of possibilities
        options: #⬅️ Possible values
        - info
        - warning
        - debug
     environment:
        description: 'Environment to run tests against'
        type: environment       
jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Log level: $LEVEL"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          ENVIRONMENT: ${{ inputs.environment }}
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:  ${{ fromJSON(vars.INPUT_VALUE) }}
       
    steps:
    - run: echo "Running Node version $version on $os"
      name: Running Node version ${{ matrix.version }} on ${{ matrix.os }}
      env:
        version: ${{ matrix.version }}
        os: ${{ matrix.os }}
        
