on:
  workflow_dispatch:
env:
  cat_name: "Puszek"
  WORKFLOW_VAR: Workflow variable
jobs:
  display-variables:
    name: ${{vars.ENVIRONMENT_VAR}}
    environment: test
    env:
      JOB_VAR: Job Variable
    runs-on: ubuntu-latest
    steps:
    - name: Use variables 1
      env:
       STEP_VAR: Step variable 1
      run: |
        echo "Repository variable : ${{vars.REPOSITORY_VAR}}"
        echo "Organization variable : ${{vars.ORGANIZATION_VAR}}"
        echo "Environment variable : ${{vars.ENVIRONMENT_VAR}}"
        echo "Alice has a cat named $cat_name"
        echo "Should be variable in workflow scope:$WORKFLOW_VAR"
        echo "Should be variable in job scope:$JOB_VAR"
        echo "Should be variable in step scope:$STEP_VAR"
    
    - name: Use variables 2
      env:
       STEP_VAR: Step variable 2
      run: |
        echo "Alice has a cat named $cat_name"
        echo "Should be variable in workflow scope:$WORKFLOW_VAR"
        echo "Should be variable in job scope:$JOB_VAR"
        echo "Should NOT be variable in step scope:$STEP_VAR"
  display-variables2:
    runs-on: ubuntu-latest
    steps:
    - name: Use variables in display-variables2
      run: |
        echo "Should be variable in workflow scope:$WORKFLOW_VAR"
        echo "Should NOT be variable in job scope:$JOB_VAR"
        echo "Should NOT be variable in step scope:$STEP_VAR"
